sudo: require
language: cpp
compiler: gcc
dist: trusty

script:
  - g++ hello.c -std=c++17 -o travis_gcc_cpp17_cppcheck
  - ./travis_gcc_cpp17_cppcheck
  - gcov hello.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
